export const FEEDBACK_LIST_REQUEST = 'FEEDBACK_LIST_REQUEST'
export const FEEDBACK_LIST_SUCCESS = 'FEEDBACK_LIST_SUCCESS'
export const FEEDBACK_LIST_FAIL = 'FEEDBACK_LIST_FAIL'

export const FEEDBACK_DELETE_REQUEST = 'FEEDBACK_DELETE_REQUEST'
export const FEEDBACK_DELETE_SUCCESS = 'FEEDBACK_DELETE_SUCCESS'
export const FEEDBACK_DELETE_FAIL = 'FEEDBACK_DELETE_FAIL'
